version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PUBLIC_URL=https://malkotohanche-api.omniscripts.eu
    env_file:
      - .env
    ports:
      - '1337:1338'
